version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=rss_agg
    networks:
      - app_rss

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "daniel99955.04@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "daniel"
    ports:
      - "6543:80"
    networks:
      - app_rss

networks:
  app_rss:
    driver: bridge
  